### PR TITLE
Finished 'team.tsx' (In need of media queries)

### PR DESCRIPTION
**Pull request by KrishKittur**

### CODE REVIEW

**Comment by TheAnnalyst** [comment]
What media queries do you need help with? I'm assuming you're going to use them to improve support on mobile devices?

**Comment by TheAnnalyst** [comment]
The test failure isn't related to your code; don't worry about it.

**Comment by KrishKittur** [comment]
> What media queries do you need help with? I'm assuming you're going to use them to improve support on mobile devices?
> 
> What does the website look like so far?
Yeah, they are just to make the website look good on mobile devices and minimized browser windows. So far, the css will look good on most computers, but not that great on phones.

**Comment by AnnikaCodes** [comment]
Did you update this based on my feedback in #base?

**Comment by TheAnnalyst** [comment]
Looks good, thanks!

**Pull request merged**
